---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.registry_file: /var/log/containers/filebeat_registry

    filebeat.prospectors:
    - type: log
      paths:
        - "/var/log/containers/*.log"
      exclude_files: ['filebeat.*log','kube.*log']
      symlinks: true
      json.message_key: log
      json.keys_under_root: true
      json.add_error_key: true
      multiline.pattern: '^\s'
      multiline.match: after
      document_type: kube-logs

    output.logstash:
        hosts: ["${LOGSTASH_HOSTS}"]
        index: ${INDEX_PREFIX}
        timeout: 15

    logging.level: ${LOG_LEVEL}
